/****************************************************************************

FILE NAME
    headset_flash_led_manager.h
    
*/

/*!

@file	headset_flash_led_manager.h
@brief converts the user event and state handling into led patterns to be used
	for LED indications.
	
	LEDs can be easily added to specific user events and states without the ned
	for configuring PSKEYS.
	
	To add a new LED pattern for a given event or state
		create the pattern in the .led file
		the led pattern will then be generated automatically using ledpars 
			(see ledparse documentation for details)
		The led pattern will then be available for use in the application.
		(the pattern name (enum) will be in the autogenerated .h file
		
		To add a new state pattern, add the pattern enum name to the 
		headsetStatePatterns table in this file.
		
		On entry to this state, then the desired pattern will display
		
		To add a new event patternm, add the pattern enum name to the 
		headsetEventPatterns table in this file.
		On receiving the event in the headset application, then the 
		desired pattern will play 
		
		
		n.b. state patterns are usually repeating patterns RPT
			 event patterns are usually non repeating patterns
			
    
*/

#ifndef ROM_LEDS

#include "headset_led_manager.h"
#include "headset_events.h"
#include "leds.h"


/*! 
    @brief a led state pattern type
	
	a different led pattern can 
*/
typedef struct
{
	unsigned normal:8;  
	unsigned low_battery:8 ;
	unsigned full_battery:8 ;
	unsigned mute:8 ;
} ledStatePattern_t ;
 
/*! 
    @brief table of LED state patterns 
	
	To add a pattern to a particular state, insert it in this table
*/
static const ledStatePattern_t ledStatePatterns [ HEADSET_NUM_STATES ] = 
{
	               /*normal ,               lowbatt ,                   fullbatt ,               mute */	
/*limbo*/	         { 0, 0 , 0 , 0 } ,
/*connectable*/	     { BLUE_TWO_FLASHES_RPT, RED_TWO_FLASHES_RPT , BLUE_TWO_FLASHES_RPT , BLUE_TWO_FLASHES_RPT } ,
/*conndiscoverable*/ { RED_BLUE_ALT_RPT_FAST, RED_BLUE_ALT_RPT_FAST , RED_BLUE_ALT_RPT_FAST, RED_BLUE_ALT_RPT_FAST } ,
/*connected*/	     { BLUE_THREE_FLASHES_RPT, RED_THREE_FLASHES_RPT , BLUE_THREE_FLASHES_RPT , BLUE_THREE_FLASHES_RPT } ,
/*outgoing*/	     { RED_BLUE_BOTH_RPT_FAST, RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST } ,
/*incoming*/	     { RED_BLUE_BOTH_RPT_FAST, RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST } ,
/*active*/	         { BLUE_SHORT_ON_RPT, RED_SHORT_ON_RPT , BLUE_SHORT_ON_RPT , RED_BLUE_ALT_RPT_FAST } ,
/*testmode*/	     { 0, 0 , 0 , 0 } ,
/*twc waiting*/	     { RED_BLUE_BOTH_RPT_FAST, RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST } ,
/*twc on hold*/	     { BLUE_TWO_FLASHES_RPT, RED_TWO_FLASHES_RPT , BLUE_TWO_FLASHES_RPT , BLUE_TWO_FLASHES_RPT } ,
/*twc multicall*/	 { BLUE_THREE_FLASHES_RPT, RED_THREE_FLASHES_RPT , BLUE_THREE_FLASHES_RPT , BLUE_THREE_FLASHES_RPT } ,
/*incoming on hold*/ { RED_BLUE_BOTH_RPT_FAST, RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST , RED_BLUE_BOTH_RPT_FAST } ,
/*active no sco*/	 { BLUE_SHORT_ON_RPT, RED_SHORT_ON_RPT , BLUE_SHORT_ON_RPT , RED_BLUE_ALT_RPT_FAST }
			
} ;
									

typedef struct 
{
	unsigned event:8 ;
	unsigned pattern:8 ;
						  
} ledEventPattern_t ;

#define ev(x) (x-EVENTS_MESSAGE_BASE)
#define NUM_LED_EVENTS (2) 
/*! 
    @brief table of LED event patterns
	
	To adda particular led pattern toa user event, add it here
*/
static const ledEventPattern_t ledEventPatterns [NUM_LED_EVENTS] = 
{
	{ ev(EventPowerOn) , LEDS_EVENT_POWER_ON } ,
	{ ev(EventPowerOff), LEDS_EVENT_POWER_OFF }
} ;


/*! 
    @brief the leds information stored and used to ccontrol the currently playing led pattern
*/
typedef struct ledsInfoTag
{
	unsigned mute:1 ;
	unsigned low_battery:1 ;
	unsigned full_battery:1 ;
	unsigned state:6 ;	
	unsigned reserved:7 ;			
}ledsInfo_t ;



static ledsInfo_t ledsInfo ;


/*!
	@brief coverts headset user events into led patterns to be played

	makes use of the auto generated LED patterns.
	
	Patterns can be defined using the .led file and autogenerated by ledparse
	
	Once generated, patterns can be assigned to events in the ledStatePatterns
	table at the top of this file
	
*/
void ledsIndicateEvent( headsetEvents_t event )  
{
	int i = 0 ;
	for (i = 0 ; i < NUM_LED_EVENTS ; i++ )
	{
		if (ledEventPatterns[i].event == ev(event) )
		{
			ledsPlay( ledEventPatterns[i].pattern ) ;
		}
	}
	
	/*change the stored state based upon the events recieved - 
		used to update the state indication*/
	switch (event)
	{
		case (EventLowBattery) :
			ledsInfo.low_battery = TRUE ;
			ledsInfo.full_battery = FALSE; 					
		break ;
		case (EventOkBattery) :
			ledsInfo.low_battery = FALSE ;
			ledsInfo.full_battery = FALSE; 							
		break ;
		case (EventMuteOn):
			ledsInfo.mute = TRUE ;
		break ;
		case (EventMuteOff):
			ledsInfo.mute = FALSE ;
		break ;
		default:
		break ;
	}		
	
		/*the state may need changing after this event has been received*/
	ledsIndicateState( ledsInfo.state )  ;
}


/*!
	@brief coverts headset user states into led patterns to be played

	makes use of the auto generated LED patterns.
	
	Patterns can be defined using the .led file and autogenerated by ledparse
	
	Once generated, patterns can be assigned to states in the ledStatePatterns
	table at the top of this file
	
*/
void ledsIndicateState( headsetState state )  
{		
		/*store the current state
		used for changing led pattern after event changes*/
	ledsInfo.state = state ;
		
	/*switch event to play based on current state*/	
	if (ledsInfo.mute)
	{
		ledsPlay( ledStatePatterns[state].normal ) ;	
	}	
	if (ledsInfo.low_battery)
	{
		ledsPlay( ledStatePatterns[state].low_battery ) ;
	}
	else if (ledsInfo.low_battery)
	{
		ledsPlay( ledStatePatterns[state].low_battery ) ;
	}
	else
	{
		ledsPlay ( ledStatePatterns[state].full_battery ) ;
	}	
}

#else
	static const int temp ;
#endif

